kind: Service
apiVersion: v1
metadata:
  name: simple-git
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: simple-httpd
  type: ClusterIP
  sessionAffinity: None
